### ISSUE TITLE
replace doubles for floats

### ISSUE THREAD

**Issue by Daankrol** [TieSoul/RayTracer#1]

**Comment by TieSoul** [comment]
why floats?

**Comment by Daankrol** [comment]
You should use floats instead of double when memory usage is critical. If you need more precise computations, use doubles.

Quote

**Comment by TieSoul** [comment]
Precise computations are more important in ray tracing than memory usage; you don't need much memory to store things since there isn't much to store; only the scene and a pixel array, which will both take up very little space in memory (less than a KB probably). Precise computations are good for ray tracing because it gives you better images with more precise shapes.
